#!python
import os
import stat

wrapper_file = '/usr/local/bin/cesium'

wrapper = '''
#!/bin/sh
python -m cesium_grpc
'''

if not os.path.exists(wrapper_file):
    with open(wrapper_file, 'w') as f:
        f.write(wrapper)
    st = os.stat(wrapper_file)
    os.chmod(wrapper_file, st.st_mode | stat.S_IEXEC)
    
